<a href="https://colab.research.google.com/github/luanmooraes/Machine-Learning/blob/main/oficina_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [ ]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(test_labels)

10000

In [ ]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [ ]:
train_images = train_images / 255.0
test_images = test_images / 255.0

In [ ]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(50, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 50)                6450      
Total params: 106,930
Trainable params: 106,930
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 2.0713 - accuracy: 0.3875
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.7510 - accuracy: 0.7433
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.6172 - accuracy: 0.7764
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.5598 - accuracy: 0.7992
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5277 - accuracy: 0.8123


In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.8090
Test accuracy: 0.8090000152587891


In [ ]:
predictions = model.predict(test_images)

In [ ]:
predictions[0]

array([6.3480779e-06, 1.9560282e-07, 1.8354098e-05, 2.1705197e-05,
       6.4286956e-05, 2.1099316e-01, 3.8426169e-05, 3.2357356e-01,
       6.7075193e-03, 4.5857581e-01, 1.6053592e-08, 1.8643886e-08,
       1.6439309e-08, 1.4940179e-08, 1.3105809e-08, 1.9025787e-08,
       1.9173328e-08, 2.1057900e-08, 1.4975271e-08, 2.2696826e-08,
       1.5595417e-08, 1.5356063e-08, 1.6156589e-08, 1.6955939e-08,
       2.1230752e-08, 1.8178513e-08, 1.8722535e-08, 1.5805638e-08,
       1.4909464e-08, 2.2510234e-08, 1.9770185e-08, 2.0138442e-08,
       1.4661581e-08, 1.4715147e-08, 1.6869713e-08, 1.3624533e-08,
       1.7237088e-08, 1.3520491e-08, 2.0566603e-08, 2.2260377e-08,
       1.8950566e-08, 1.8545149e-08, 1.1886022e-08, 1.6278431e-08,
       1.5466616e-08, 2.0568917e-08, 1.9329345e-08, 1.3245483e-08,
       1.8320319e-08, 2.2954254e-08], dtype=float32)

In [ ]:
np.argmax(predictions[0])

9

In [ ]:
test_labels[0]

9

In [ ]:
img = test_images[0]

print(img.shape)

(28, 28)


In [ ]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [ ]:
predictions_single = model.predict(img)

print(predictions_single)

[[6.34807293e-06 1.95603036e-07 1.83541015e-05 2.17052220e-05
  6.42869636e-05 2.10993096e-01 3.84261402e-05 3.23573500e-01
  6.70751790e-03 4.58575904e-01 1.60536242e-08 1.86438900e-08
  1.64393104e-08 1.49401824e-08 1.31058115e-08 1.90257925e-08
  1.91733314e-08 2.10579056e-08 1.49752726e-08 2.26968737e-08
  1.55954201e-08 1.53560364e-08 1.61565907e-08 1.69559424e-08
  2.12308375e-08 1.81784809e-08 1.87225382e-08 1.58056412e-08
  1.49094372e-08 2.25101964e-08 1.97701890e-08 2.01384847e-08
  1.46615839e-08 1.47151500e-08 1.68696843e-08 1.36245353e-08
  1.72370918e-08 1.35204674e-08 2.05666471e-08 2.22603820e-08
  1.89505336e-08 1.85451174e-08 1.18860477e-08 1.62784026e-08
  1.54665898e-08 2.05689616e-08 1.93293861e-08 1.32454607e-08
  1.83202875e-08 2.29542572e-08]]


In [ ]:
np.argmax(predictions_single[0])

9